### ISSUE TITLE
Fix for dynamicHelpers?

### ISSUE THREAD

**Issue by chrisdew** [kalmiz/express-dust#1]
Hi Kalmiz

Does your fork fix https://github.com/davglass/express-dust/issues/3

Thanks,

Chris.

**Comment by kalmiz** [comment]
Hi Chris

My express-dust is not a fork of davglass's express-dust, but I my lib is support dynamicHelpers. 
I will upload some examples soon.
(It seems davglass and me started express-dust at same time. Funny.)

**Comment by chrisdew** [comment]
Would you consider renaming your express-dust and publishing an npm package?  Could I suggest 'dust-express'?

Really we need to get _some version_ of dust-express into the upstream dust and full integration with express.  Is anyone working towards this?

I'll hack your current code into my project and give it a try,

Thanks,

Chris,

**Comment by chrisdew** [comment]
Just got this to work in my project:

```
var express_dust = require('./support/express-dust/lib/express-dust');

app.configure(function(){
  //app.set('view engine', 'express-dust');
  app.set('view engine', 'dust');
  express_dust.register(app);
```

A few proper examples would be very welcome though.

Thanks,

Chris.

**Comment by chrisdew** [comment]
Oops closed by accident.  Waiting for a few examples before closing this ticket.

**Comment by kalmiz** [comment]
I uploaded a simple example in the examples folder. Check it out please.

**Comment by chrisdew** [comment]
Thanks, that's great.

I've used your express-dust in a little project I'm testing -  https://www.tipslate.org/

There's a discussion at http://groups.google.com/group/long-week-startups/browse_thread/thread/d8ed2d6d1363117f#

Thanks for writing this.  I'll send a donation on Tipslate, once it's working (probably a month or two).

All the best,

Chris.
